### ISSUE TITLE
What should this sim and repo be named?

### ISSUE THREAD

**Issue by samreid** [phetsims/sound-waves#2]
On Monday Sept 26, @samreid said in a slack message with @arouinfar and @kathy-phet 👍 

> Hi Kathy & Amy, I responded to an email about incorporating a 3rd party (Jan and Piet) implementation of the PhET Sound simulation into our codebase.  What do you want to call the repo + sim name for the HTML implementation?  It looks like the repo name in Java was “sound”, and the Java title was “Sound Waves”.

@arouinfar replied:

> Are you talking about [this sim](https://phet.colorado.edu/en/simulations/sound)? Seems like it’s just called “Sound”. I double checked the sim itself and the name in the table on the Admin > Simulations page.

I replied:

> OK sounds good, thanks

Today @pixelzoom said:

> Based on your other posts, I’m guessing this is a new sim. And I’m sort of surprised by such a generic-sounding sim name.

**Comment by arouinfar** [comment]
This sim is not currently a priority, so unassigning myself.

**Comment by matthew-blackman** [comment]
@kathy-phet should the HTML5 port of the sim still be called 'Sound'?

**Comment by matthew-blackman** [comment]
I agree that the name 'sound' makes the repo sound like common code. Personally I would be in favor of 'Sound Waves', since the learning goals fall under the 'waves' unit in physics. I also noticed that all other wave-related sims have the word "waves" in the title, so it would be good to keep this keyword in the title (see below).

<img width="1278" alt="Screen Shot 2023-08-17 at 9 59 22 AM" src="https://github.com/phetsims/sound/assets/108756567/37c8b1fb-9dd6-40d9-b9ea-319764dd2090">

Thoughts @arouinfar?

**Comment by arouinfar** [comment]
@matthew-blackman makes a really great case for "Sound Waves". Let's go with it.

**Comment by kathy-phet** [comment]
Sounds good! :)

**Comment by samreid** [comment]
For @matthew-blackman reference, here is a "rename repo" checklist: https://github.com/phetsims/phet-info/blob/master/checklists/rename-repo-checklist.md

**Comment by matthew-blackman** [comment]
The repo name has been changes to Sound Waves! Closing.
