### ISSUE TITLE
Is it possible to increase font size?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/sound-waves#29]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/972, the font size is unusually small in this sim. I know this is meant to be a quick release, but I wanted to mention it. 

Here is a comparison with Gravity and Orbits:
<img width="615" alt="Screenshot 2023-08-21 at 3 30 26 PM" src="https://github.com/phetsims/sound-waves/assets/87318828/68a4200d-863b-4b7e-a76f-941e29073b2a">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Sound Waves‬
URL: https://phet-dev.colorado.edu/html/sound-waves/1.0.0-dev.5/phet/sound-waves_all_phet.html?
Version: 1.0.0-dev.5 2023-08-21 17:16:24 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15
Language: en-US
Window: 1099x624
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
Also, the location of the frequency readout makes it look like it is the value of the middle tick mark. The java version had the value off-center with more space between it and the scale. 
 
<img width="407" alt="Screenshot 2023-08-22 at 8 23 29 AM" src="https://github.com/phetsims/sound-waves/assets/87318828/bf5a2de2-b8cb-4cc3-98b8-912402af7b19">

**Comment by Nancy-Salpepi** [comment]
Font looks much better! I can actually read it! haha

**Comment by matthew-blackman** [comment]
Reopening to confirm during next dev test.

**Comment by KatieWoe** [comment]
Looks much better to me. I did notice that the "ATM" on the pressure gauge on the Air Pressure screen was a bit small. Is that worth a look?
![atm](https://github.com/phetsims/sound-waves/assets/41024075/c8eff9d0-4a8b-4db9-9dd0-78b9d4745b10)

**Comment by matthew-blackman** [comment]
I expanded the options of GaugeNode to allow a custom font size for the label, and also increased the font of the numerical labels  on the pressure gauge. @KatieWoe can you spot-check on main?

@samreid might be good to get a review here as well since GaugeNode is a scenery component. Let me know if you have any questions!

**Comment by samreid** [comment]
Thanks, looks good and I have a few recommendations for next steps:

1. Let's name the option "label" instead of "title" to match with existing terminology.
2. Let's convert to the nested options pattern. So it would become `labelTextOptions: TextOptions`. We'll still need to `combineOptions` to get the tandem. Let's leave the existing logic for maxWidth. See NumberControl for an example of the nested options pattern: https://github.com/phetsims/scenery-phet/blob/234fc50e13fee7c04ee9e79bc62f4539475e6a24/js/NumberControl.ts#L164

**Comment by KatieWoe** [comment]
Looks ok to me on main

**Comment by matthew-blackman** [comment]
Thanks for the feedback @samreid! I gave this a try in the above commits.

**Comment by KatieWoe** [comment]
Looks good on main

**Comment by Nancy-Salpepi** [comment]
Font size looks good to me in rc.2. Closing.
